name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: version name
        run: go test -cover ./...


   style:
     name:Formatting
     runs-on:ubuntu-latest

   steps:
    - name: check out code
      uses: actions/checkout@v4

   - name: set up go
     uses: actions/setup-go@v5
     with:
      go-version: "1.25.1"

   - name: fortamatting
     run: test -z $(go fmt ./...)
